Polish up a couple things
- Rename prod -> production for consistency
- Don't bash -x by default to avoid logging passwords by accident
- Add an import script for use on remote host
- Add missing volume declaration to docker-compose
- Add more complicated environment variable verification to analytics
  entrypoint script to support empty debug environment variable

diff --git a/analytics/entrypoint b/analytics/entrypoint
--- a/analytics/entrypoint
+++ b/analytics/entrypoint
@@ -1,6 +1,32 @@
 #!/usr/bin/env bash
 
-set -eux
+set -e
+
+if [[ -n "$GOATCOUNTER_DEBUG" ]]; then
+  set -x
+fi
+
+fail="no"
+
+required_vars=(GOATCOUNTER_DB GOATCOUNTER_DOMAIN)
+firstrun_vars=(GOATCOUNTER_EMAIL GOATCOUNTER_PASSWORD)
+
+for var in "${required_vars[@]}"; do
+  if [[ -z "${!var}" ]]; then
+    echo "ERROR: Required environment variable \$${var} not set"
+    fail="yes"
+  fi
+done
+
+for var in ${firstrun_vars[@]}; do
+  if [[ -z "${!var}" ]]; then
+    echo "WARNING: First run environment variable \$${var} not set, this may fail"
+  fi
+done
+
+if [[ "$fail" = "yes" ]]; then
+  exit 1
+fi
 
 find_site() {
   goatcounter db show site\
